### ISSUE TITLE
AuthorizationHeaderPayload should use getResponse()?

### ISSUE THREAD

**Issue by monstrfolk** [raphaelDL/spring-webflux-security-jwt#6]
Should AuthorizationHeaderPayload be using getResponse()?

https://github.com/raphaelDL/spring-webflux-security-jwt/blob/master/src/main/java/io/rapha/spring/reactive/security/auth/jwt/AuthorizationHeaderPayload.java#L29

`public class AuthorizationHeaderPayload {

    public static Mono<String> extract(ServerWebExchange serverWebExchange) {
        return Mono.justOrEmpty(serverWebExchange.getResponse()
                .getHeaders()
                .getFirst(HttpHeaders.AUTHORIZATION));
    }
}`

**Comment by raphaelDL** [comment]
We use `serverWebExchange.getRequest()` because in this step we are filtering the current request, that's why we need to extract the contents form the Authorization Header. 
Care to elaborate more about your question?

**Comment by monstrfolk** [comment]
After logging in the only authorization header I see in the request is "Basic dXNlcjp1c2Vy". This fails token validation at https://github.com/raphaelDL/spring-webflux-security-jwt/blob/master/src/main/java/io/rapha/spring/reactive/security/auth/jwt/JWTCustomVerifier.java#L45

**Comment by raphaelDL** [comment]
Yes, and in the response you’ll get a Bearer token in the authorization header, you copy/use that token in your next request instead of basic credentials

**Comment by raphaelDL** [comment]
You first login using basic in order to get a token, then put that token in another request authorization header to consume the api

**Comment by monstrfolk** [comment]
Thanks for explanation. The Mono.empty() was messing me up because api/* pages were returning data after login without Authorization header with Bearer.
